config/routes.rb
Rails.application.routes.draw do
  root to: "places#index"
  resources :counties
  resources :cities
  resources :edutypes
  resources :places
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/edutypes_controller.rb
class EdutypesController < ApplicationController
  before_action :set_edutype, only: [:show, :edit, :update, :destroy]
  layout 'generic'

  # GET /edutypes
  # GET /edutypes.json
  def index
    @edutypes = Edutype.all
  end

  # GET /edutypes/1
  # GET /edutypes/1.json
  def show
  end

  # GET /edutypes/new
  def new
    @edutype = Edutype.new
  end

  # GET /edutypes/1/edit
  def edit
  end

  # POST /edutypes
  # POST /edutypes.json
  def create
    @edutype = Edutype.new(edutype_params)

    respond_to do |format|
      if @edutype.save
        format.html { redirect_to @edutype, notice: 'Edutype was successfully created.' }
        format.json { render :show, status: :created, location: @edutype }
      else
        format.html { render :new }
        format.json { render json: @edutype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /edutypes/1
  # PATCH/PUT /edutypes/1.json
  def update
    respond_to do |format|
      if @edutype.update(edutype_params)
        format.html { redirect_to @edutype, notice: 'Edutype was successfully updated.' }
        format.json { render :show, status: :ok, location: @edutype }
      else
        format.html { render :edit }
        format.json { render json: @edutype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /edutypes/1
  # DELETE /edutypes/1.json
  def destroy
    @edutype.destroy
    respond_to do |format|
      format.html { redirect_to edutypes_url, notice: 'Edutype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edutype
      @edutype = Edutype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edutype_params
      params.require(:edutype).permit(:name)
    end
end

app/helpers/edutypes_helper.rb
module EdutypesHelper
end

app/views/edutypes/_form.html.erb
<%= form_for(edutype, html: { class: "form-inline" }) do |f| %>
  <% if edutype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(edutype.errors.count, "error") %> prohibited this edutype from being saved:</h2>

      <ul>
      <% edutype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <br>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/edutypes/edit.html.erb
<h1>Editing Edutype</h1>

<%= render 'form', edutype: @edutype %>

app/views/edutypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Edutypes</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @edutypes.each do |edutype| %>
      <tr>
        <td><%= edutype.name %></td>
        <td><%= link_to 'Show', edutype %></td>
        <td><%= link_to 'Edit', edit_edutype_path(edutype) %></td>
        <td><%= link_to 'Destroy', edutype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/edutypes/new.html.erb
<h1>New Edutype</h1>

<%= render 'form', edutype: @edutype %>

app/views/edutypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @edutype.name %>
</p>

<%= link_to 'Edit', edit_edutype_path(@edutype) %> |
<%= link_to 'Back', edutypes_path %>