config/routes.rb
Rails.application.routes.draw do
  root to: "places#index"
  resources :counties
  resources :cities
  resources :edutypes
  resources :places
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/county.rb
class County < ApplicationRecord
  has_many :places
end

app/controllers/counties_controller.rb
class CountiesController < ApplicationController
  before_action :set_county, only: [:show, :edit, :update, :destroy]
  layout 'generic'

  # GET /counties
  # GET /counties.json
  def index
    @counties = County.all
  end

  # GET /counties/1
  # GET /counties/1.json
  def show
  end

  # GET /counties/new
  def new
    @county = County.new
  end

  # GET /counties/1/edit
  def edit
  end

  # POST /counties
  # POST /counties.json
  def create
    @county = County.new(county_params)

    respond_to do |format|
      if @county.save
        format.html { redirect_to @county, notice: 'County was successfully created.' }
        format.json { render :show, status: :created, location: @county }
      else
        format.html { render :new }
        format.json { render json: @county.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /counties/1
  # PATCH/PUT /counties/1.json
  def update
    respond_to do |format|
      if @county.update(county_params)
        format.html { redirect_to @county, notice: 'County was successfully updated.' }
        format.json { render :show, status: :ok, location: @county }
      else
        format.html { render :edit }
        format.json { render json: @county.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counties/1
  # DELETE /counties/1.json
  def destroy
    @county.destroy
    respond_to do |format|
      format.html { redirect_to counties_url, notice: 'County was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_county
      @county = County.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def county_params
      params.require(:county).permit(:name)
    end
end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/views/counties/_form.html.erb
<%= form_for(county, html: { class: "form-inline" }) do |f| %>
  <% if county.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(county.errors.count, "error") %> prohibited this county from being saved:</h2>

      <ul>
      <% county.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <br>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/counties/edit.html.erb
<h1>Editing County</h1>

<%= render 'form', county: @county %>

app/views/counties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Counties</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @counties.each do |county| %>
      <tr>
        <td><%= county.name %></td>
        <td><%= link_to 'Show', county %></td>
        <td><%= link_to 'Edit', edit_county_path(county) %></td>
        <td><%= link_to 'Destroy', county, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/counties/new.html.erb
<h1>New County</h1>

<%= render 'form', county: @county %>

app/views/counties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @county.name %>
</p>

<%= link_to 'Edit', edit_county_path(@county) %> |
<%= link_to 'Back', counties_path %>