config/routes.rb
Rails.application.routes.draw do
  root to: "places#index"
  resources :counties
  resources :cities
  resources :edutypes
  resources :places
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :city
  belongs_to :county
  belongs_to :edutype
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  layout 'generic'

  # GET /places
  # GET /places.json
  def index
    params[:per_page] ||= 100
    @q = Place.includes(:city, :county, :edutype).ransack(params[:q])
    @results = @q.result
    @places = @results.page(params[:page]).per(params[:per_page])
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :title, :site, :address, :postal_code, :phone, :fax, :permission_code, :edutype, :amea, :trainee_capacity, :city, :county)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(place, html: { class: "form-inline" }) do |f| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :site %>
    <%= f.text_field :site, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :postal_code %>
    <%= f.number_field :postal_code, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :fax %>
    <%= f.text_field :fax, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :permission_code %>
    <%= f.number_field :permission_code, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :edutype %>
    <%= f.number_field :edutype, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :amea %>
    <%= f.check_box :amea, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :trainee_capacity %>
    <%= f.number_field :trainee_capacity, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.number_field :city, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :county %>
    <%= f.number_field :county, class: "form-control" %>
  </div>

  <br>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<hr>
<%= search_form_for @q do |f| %>

  <%= f.label :name_cont %>
  <%= f.search_field :name_cont, class: "form-control" %>

  <%= f.label :title_cont %>
  <%= f.search_field :title_cont, class: "form-control" %>

  <%= f.label :site_cont %>
  <%= f.search_field :site_cont, class: "form-control" %>

  <%= f.label :postal_code_cont %>
  <%= f.search_field :postal_code_cont, class: "form-control" %>

  <%= f.label :phone_cont %>
  <%= f.search_field :phone_cont, class: "form-control" %>

  <%= f.label :fax_cont %>
  <%= f.search_field :fax_cont, class: "form-control" %>

  <%= f.label :permission_code_cont %>
  <%= f.search_field :permission_code_cont, class: "form-control" %>

  <%#= f.label :amea_cont %>
  <%#= f.search_field :amea_cont, class: "form-control" %>

  <%= f.label :trainee_capacity_gteq %>
  <%= f.search_field :trainee_capacity_gteq, class: "form-control" %>

  <%= f.label :trainee_capacity_lteq %>
  <%= f.search_field :trainee_capacity_lteq, class: "form-control" %>

  <%= f.label :county_id_eq %>
  <%= f.select :county_id_eq, options_from_collection_for_select(County.order(:name), "id", "name", @q.county_id_eq), include_blank: true %>

  <%= f.label :edutype_id_eq %>
  <%= f.select :edutype_id_eq, options_from_collection_for_select(Edutype.order(:name), "id", "name", @q.edutype_id_eq), include_blank: true %>

  <%= f.label :city_id_eq %>
  <%= f.select :city_id_eq, options_from_collection_for_select(City.order(:name), "id", "name", @q.city_id_eq), include_blank: true %>

  <%= f.submit %>
<% end %>
<hr>
<div>
  Αριθμός αποτελέσματων:
  <%= @results.count %>
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= sort_link(@q, :name) %></th>
      <th><%= sort_link(@q, :title) %></th>
      <th><%= sort_link(@q, :site) %></th>
      <th><%= sort_link(@q, :address) %></th>
      <th><%= sort_link(@q, :postal_code) %></th>
      <th><%= sort_link(@q, :phone) %></th>
      <th><%= sort_link(@q, :fax) %></th>
      <th><%= sort_link(@q, :permission_code) %></th>
      <th><%= sort_link(@q, :amea) %></th>
      <th><%= sort_link(@q, :trainee_capacity) %></th>
      <th>City</th>
      <th>Edutype</th>
      <th>County</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.title %></td>
        <td><%= place.site %></td>
        <td><%= place.address %></td>
        <td><%= place.postal_code %></td>
        <td><%= place.phone %></td>
        <td><%= place.fax %></td>
        <td><%= place.permission_code %></td>
        <td><%= place.amea %></td>
        <td><%= place.trainee_capacity %></td>
        <td><%= place.city.try(:name) %></td>
        <td><%= place.edutype.try(:name) %></td>
        <td><%= place.county.try(:name) %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @places %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @place.title %>
</p>

<p>
  <strong>Site:</strong>
  <%= @place.site %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @place.postal_code %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @place.phone %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @place.fax %>
</p>

<p>
  <strong>Permission code:</strong>
  <%= @place.permission_code %>
</p>

<p>
  <strong>Edutype:</strong>
  <%= @place.edutype.name %>
</p>

<p>
  <strong>Amea:</strong>
  <%= @place.amea %>
</p>

<p>
  <strong>Trainee capacity:</strong>
  <%= @place.trainee_capacity %>
</p>

<p>
  <strong>City:</strong>
  <%= @place.city.name %>
</p>

<p>
  <strong>County:</strong>
  <%= @place.county.name %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>